# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tim Maguire
Author: Tim Maguire
description: >- # this means to ignore newlines until "baseurl:"
  Tim Maguire's writing and thoughts on APIs.  Tim has been a Product Manager in the API space since 2018.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tmaguire.net" # the base hostname & protocol for your site, e.g. http://example.com


github_username:  fluffhead-tim
mastodon:
 - username: TimMaguire
   instance: hachyderm.io

   
linkedin_username: tmaguire
#twitter_username: tmaguire720
#  {%- for mst in site.mastodon -%}{%- if mst.username and mst.instance -%}<li><a href="https://{{ mst.instance| cgi_escape | escape}}/@{{mst.username}}"><svg class="svg-icon"><use xlink:href="{{ '/assets/minima-social-icons.svg#mastodon' | relative_url }}"></use></svg> <span class="username">{{ mst.username|escape }}</span></a></li>{%- endif -%}{%- endfor -%}

#social-network-links:
#  email: tim&#64;tmaguire&#46;net
#  bluesky: tmaguire.net
#  github: fluffhead-tim
#  linkedin: tmaguire
#  mastodon:
#    - username: TimMaguire
#      instance: hachyderm.io

#social_links:
#  - { platform: github,  user_url: "https://github.com/fluffhead-tim" }
#  - { platform: twitter, user_url: "https://twitter.com/tmaguire720" }

#add google analytics
google_analytics: G-580E99WPK1

# Build settings
theme: minima
plugins:
  - jekyll-feed

#show an excerpt on the home page:
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
